<!DOCTYPE html>
<html>
<body>
    <div>
        <ul class="regular slider">
            <li><img src="<?php echo $this->getViewFileUrl('images/bag-1.jpg'); ?>" alt="demo" /></li>
            <li><img src="<?php echo $this->getViewFileUrl('images/bag-2.jpg'); ?>" alt="demo" /></li>
            <li><img src="<?php echo $this->getViewFileUrl('images/bag-3.jpg'); ?>" alt="demo" /></li>
            <li><img src="<?php echo $this->getViewFileUrl('images/bag-1.jpg'); ?>" alt="demo" /></li>
            <li><img src="<?php echo $this->getViewFileUrl('images/bag-2.jpg'); ?>" alt="demo" /></li>
            <li><img src="<?php echo $this->getViewFileUrl('images/bag-3.jpg'); ?>" alt="demo" /></li>
            <li><img src="<?php echo $this->getViewFileUrl('images/bag-1.jpg'); ?>" alt="demo" /></li>
            <li><img src="<?php echo $this->getViewFileUrl('images/bag-2.jpg'); ?>" alt="demo" /></li>
            <li><img src="<?php echo $this->getViewFileUrl('images/bag-3.jpg'); ?>" alt="demo" /></li>
            <li><img src="<?php echo $this->getViewFileUrl('images/bag-1.jpg'); ?>" alt="demo" /></li>
        </ul>
        
    </div>
</body>
</html>